language: java
sudo: false
jdk:
  - oraclejdk8

branches:
  only:
    - master

script:
  - mvn clean
  - mvn verify

after_success:
  - mvn sonar:sonar -Dsonar.organization=${SONAR_ORGANIZATION} -Dsonar.login=${SONAR_TOKEN} -Dsonar.host.url=${SONAR_HOST}
