language: java
sudo: true
jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
  - chmod +x mvnw

script:
  - ./mvnw clean
  - ./mvnw verify

after_success:
  - ./mvnw sonar:sonar -Dsonar.organization=${SONAR_ORGANIZATION} -Dsonar.login=${SONAR_TOKEN} -Dsonar.host.url=${SONAR_HOST}
